---
application:
  name: "aanwezigheden-backend"
  project: "aanwezigheden"
  organization: "QoveryCommunity"
routers:
- name: "main-aanwezigheden-backend"
  routes:
  - application_name: "aanwezigheden-backend"
    paths:
    - "/*"
